
var customStyle = {
    iframe : {
        showCardTypeIcons : true,
        language : 'en',
        backgroundColor: '#e5e5e5',
        fields: {
            generic: {
                width: '100%',
                backgroundColor: 'white',
                backgroundColorFocus: '#e5ecff',
                backgroundColorError: '#ffe5e5',
                backgroundColorValid: '#e5ffec',
                textColor: 'black',
                textColorFocus: 'black',
                textColorError: 'red',
                textColorValid: 'green',
                labelTextColor: '#828282',
                labelTextColorError: 'red',
                labelTextColorValid: 'green',
                border: '1px solid #b4b4b4',
                borderRadius: '',
                borderError: '1px solid #ff0000'
            },
            // Field properties will take priority if defined
            cardNumber: {
                labelText: 'Card Number',
                placeholderText: 'Card Number',
                x: '',
                y: '',
                width: '',
                height: '',
                backgroundColor: '',
                backgroundColorFocus: '',
                backgroundColorError: '',
                backgroundColorValid: '',
                textColor: '',
                textColorFocus: '',
                textColorError: '',
                textColorValid: '',
                labelTextColor: '',
                labelTextColorError: '',
                labelTextColorValid: '',
                border: '',
                borderRadius: '',
                borderError: ''
            },
            expiryDate: {
                labelText: 'Expiry Date',
                placeholderText: 'MM/YY',
                x: '',
                y: '',
                width: '',
                height: '',
                backgroundColor: '',
                backgroundColorFocus: '',
                backgroundColorError: '',
                backgroundColorValid: '',
                textColor: '',
                textColorFocus: '',
                textColorError: '',
                textColorValid: '',
                labelTextColor: '',
                labelTextColorError: '',
                labelTextColorValid: '',
                border: '',
                borderRadius: '',
                borderError: ''
            },
            cv2: {
                labelText: 'CVC',
                placeholderText: 'CVC',
                x: '',
                y: '',
                width: '',
                height: '',
                backgroundColor: '',
                backgroundColorFocus: '',
                backgroundColorError: '',
                backgroundColorValid: '',
                textColor: '',
                textColorFocus: '',
                textColorError: '',
                textColorValid: '',
                labelTextColor: '',
                labelTextColorError: '',
                labelTextColorValid: '',
                border: '',
                borderRadius: '',
                borderError: ''
            }
        }
    }
};
